---
# Nginx reverse proxy configuration
- name: Install nginx
  dnf:
    name: nginx
    state: present
  tags: nginx-install

- name: Create nginx main configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: reload nginx
  tags: nginx-config

- name: Create project88 nginx configuration
  template:
    src: project88-nginx.conf.j2
    dest: "/etc/nginx/conf.d/project88-{{ environment }}.conf"
  notify: reload nginx
  tags: nginx-site

- name: Remove default nginx site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx
  tags: nginx-cleanup

- name: Create nginx log directory
  file:
    path: /var/log/nginx/project88
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  tags: nginx-logs

- name: Enable and start nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started
  tags: nginx-service