---
# Default variables for backup role
app_user: appuser
app_group: appuser
backup_base_dir: /opt/project88/backup

# S3 configuration
s3_bucket: "{{ vault_s3_bucket }}"
s3_region: us-east-1
s3_access_key: "{{ vault_s3_access_key }}"
s3_secret_key: "{{ vault_s3_secret_key }}"

# Backup retention (days)
daily_retention: 30
weekly_retention: 90
monthly_retention: 365

# Database configuration
postgres_host: localhost
postgres_port: "{{ postgres_port | default(5432) }}"
postgres_db: "{{ postgres_db }}"
postgres_user: "{{ postgres_user }}"
postgres_password: "{{ vault_postgres_password }}"

# Development database refresh configuration
dev_db_record_limit: 500
dev_refresh_enabled: true

# Tables to keep full in dev (multi-tenant and core config)
dev_full_tables:
  - timing_partners
  - users
  - providers
  - system_settings

# Tables to trim in dev (large data tables)
dev_trim_tables:
  - ct_events
  - ct_participants
  - ct_results
  - runsignup_events
  - runsignup_participants
  - raceroster_events
  - raceroster_participants
  - haku_events
  - haku_participants
  - letsdothis_events
  - letsdothis_participants
  - raw_tag_data
  - sync_history

# Monitoring configuration
backup_monitor_enabled: true
backup_alert_threshold_hours: 26

# File backup paths
backup_paths:
  - /opt/project88
  - /etc/project88
  - /var/log/project88